Per illustration, added a smaal example piece of code from original jack authors.

diff --git a/build_with_simpledsp b/build_with_simpledsp
--- a/build_with_simpledsp
+++ b/build_with_simpledsp
@@ -9,6 +9,23 @@ fi
 libSimpleDsp="$1"
 shift
 
+doCleanSimpleDsp=""
+doRun=""
+
+while test "x$1" != "x"
+do
+	if test "$1" = "run"
+	then
+		doRun="yes"
+		echo "Runnign speakerman after build"
+	elif test "$1" = "clean"
+	then
+		doCleanSimpleDsp="yes"
+		echo "Also clean simpledsp project"
+	fi
+	shift
+done
+
 if test "x$1" = "xrun"
 then
 	doRun="yes"
@@ -26,6 +43,16 @@ if ! cd "${libSimpleDsp}"
 then
 	echo "Couldn't change to ${libSimpleDsp}"
 	exit 1
+fi
+
+if test -n "$doCleanSimpleDsp"
+then
+	echo "Cleaning simpledsp project first"
+	if ! make clean
+	then
+		echo "Couldn't clean simpledsp project"
+		exit 1
+	fi
 fi
 
 if ! make -j 
